"""Regression test: the 5 mapped continuum-residence-01 rooms must serve the
real static stock photo (byte-identical to backend/static/stock_photos/),
and every other room in the unit must be unaffected (still generated by the
image provider)."""
import hashlib
from pathlib import Path

import app.config as cfg
from app.pipeline import generate_unit
from app.static_room_images import STATIC_ROOM_IMAGES

ROOT = Path(__file__).resolve().parents[1]
PLAN = ROOT / "source_continuum_residence_01.jpg"
STATIC_DIR = ROOT / "static"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def test_mapped_rooms_serve_the_real_static_photo_unmapped_rooms_unaffected():
    out = ROOT / "renders_static_image_test"
    old = cfg.settings.out_dir
    cfg.settings.out_dir = str(out)
    try:
        manifest = generate_unit("continuum-residence-01", PLAN, provider="mock")
        unit_dir = out / "continuum-residence-01"

        mapped = STATIC_ROOM_IMAGES["continuum-residence-01"]
        assert set(mapped) == {"great", "kitchen", "terrace", "primary", "pbath"}

        for rid, rel_path in mapped.items():
            rendered = unit_dir / f"{rid}.jpg"
            source = STATIC_DIR / rel_path
            assert rendered.exists()
            assert _sha256(rendered) == _sha256(source), (
                f"{rid}: rendered file does not match the real static photo bytes"
            )

        # Unmapped rooms must still exist and must NOT match any static photo
        # (they were genuinely generated by the mock provider, not overridden).
        static_hashes = {_sha256(STATIC_DIR / p) for p in mapped.values()}
        unmapped = [rid for rid in manifest["order"] if rid not in mapped]
        assert set(unmapped) == {"bed2", "bed3", "bath2", "bath3", "powder"}
        for rid in unmapped:
            rendered = unit_dir / f"{rid}.jpg"
            assert rendered.exists()
            assert _sha256(rendered) not in static_hashes
    finally:
        cfg.settings.out_dir = old
